version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    ports:
      - "5000:5000"

  tunnel:
    restart: always
    image: cloudflare/cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiOTI5YjQ0ODBlMzhkMmYwMTI2NzQzMDQ1OWM3NzUxMjciLCJ0IjoiOGM4OTBiZGYtNjYwZS00YjI5LTkzNGUtMTI3ZGYyZTlhNDI4IiwicyI6IllUSTJaV1EzWmpVdE5HWTBNeTAwTkdVNExUazRabVF0TVRGak9UQTJORFF4TWpnMSJ9